### ISSUE TITLE
Unable to switch languages

### ISSUE THREAD

**Issue by flysiunb** [Half-People/HImGuiEditor#10]
Loading progress bar ends without switching languages
![微信截图_20240110005831](https://github.com/Half-People/HImGuiEditor/assets/140980081/1f4cdd7b-41b9-4ba7-a38d-309200669675)

**Comment by Half-People** [comment]
抱歉我现在比较忙 我本来想着把 `node editor`功能做了再一次更新的 这个功能已经做好了 可能有晚一点才能更新噢
