### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by apol3t** [Half-People/HImGuiEditor#7]
Could you make a plugin system tutorial ? 
i don't know how to add plugins

**Comment by Half-People** [comment]
yes i can

**Comment by apol3t** [comment]
thanks sir

**Comment by Half-People** [comment]
Dude can you take a look and see if you understand what I'm saying if not I'll make a wiki   Because my English is very poor. As a Hong Kong native, but my English is really poor and I usually get 0 points. sorry
https://youtu.be/06dZUHFoEvY

**Comment by apol3t** [comment]
Thank you for the tutorial.
Your English is not so bad, I can understand you. Thanks again for your very helpful help.
