### ISSUE TITLE
some bug or errors

### ISSUE THREAD

**Issue by apol3t** [Half-People/HImGuiEditor#8]
After saving the project to the latest version, when I try to open it again, it does not open. exporting the project into visual studio doesn't work either. Is the problem with me? Can you check it ?

**Comment by Half-People** [comment]
Can you explain your operation method to me in detail?
It's true that there is a little bug that I haven't fixed yet. 
thx

**Comment by Half-People** [comment]
If it is a plug-in problem, it may be caused by the last update. You can copy and update the main code.

**Comment by apol3t** [comment]
I'm at work now . I'll check it when I'm done. I will share detailed information later

**Comment by apol3t** [comment]
I checked the latest version you published and the registration problem is gone. There is no other problem I have encountered so far. thank you very much for doing this project
